### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by fraxken** [lukeed/httpie#28]
Hi,

I'm switching to the next version to be able to use the timeout option but doesn't seem to work. I'm using it with CJS by the way.

Pkg version: ^2.0.0-next.8
Node version: 14.2.0

```bash
internal/modules/cjs/loader.js:491
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in F:\Code\SlimIO\Npm-registry\node_modules\httpie\package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\Code\SlimIO\Npm-registry\index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I guess there something wrong with the CJS Export ? I have not updated my code so i require like this
```js
const { get } = require("httpie");
```

Best Regards,
Thomas

**Comment by lukeed** [comment]
Thanks! I encountered this last night too, but I was having ISP issues so my publish and git-push failed.

And then I forgot to do it this morning 😅 Thanks for reminder. It's up now on `httpie@2.0.0-next.9`

**Comment by fraxken** [comment]
@lukeed no problem! Thanks for your work and as always your reactivity :)
